### DISCUSSION TITLE
Multilingual support for notifications and system messages

### DISCUSSION THREAD

**Discussion by StefanMunnes** [surveydown-dev/surveydown#134] [Feature Requests]
### Description

For all people who create non-English surveys, such as myself with mainly German surveys, I would find it useful to have a multilingual option for the standard text output.

As far as I can see, this concerns the warning messages for required questions, the final page, survey rating, redirect and the standard values for next and exit survey buttons. There are also validation output for function arguments (e.g. `sd_output(type)`). 
I'm not talking about error messages in general or the admin page, just what the survey participants might see.

To achieve this, I would have an additional config YAML/JSON or R file that hast all provided translations and the option in the yaml-header in the survey.qmd file to choose the correct language. One could also think about the possibility for the user, to provide an additional config file in their project folder, if the needed language is not available from default.

translations.yml
```yaml
en:
  next_button: "Next"
  exit_survey:  "Are you sure you want to exit the survey?"
  required_response: "Please answer all required questions before proceeding."
de:
  next_button: "Weiter"
  exit_survey: "Sind Sie sicher, dass Sie die Umfrage verlassen möchten?"
  required_response: "Bitte beantworten Sie alle Pflichtfragen, bevor Sie fortfahren."
````

survey.qmd
```md
---
format: html
echo: false
warning: false
language: "de" # or "fr", etc.
---
```

If you like this idea, I'm willing to prepare a PR.
