### DISCUSSION TITLE
Validate text question's response before next question

### DISCUSSION THREAD

**Discussion by cwilligv** [surveydown-dev/surveydown#206] [Q&A]
### Description

I'm designing a survey which first question is an identifier that is stored in a DB. I need to validate whether that ID exists before moving to the next question. I tried doing it with show_if/conditional but I can't make it work for a text-type question. 

For example:

In questions.yml I have my text question defined as:
```
q0:
  type: text
  label: 'Provide your Identification number'
  options:
    '': Example 12345678
```

in survey.qmd I have the following
```
sd_question("q0")
sd_next()
```

And in server I have this:
```
valid_number <- function(q){
   return (if (q is in db) then TRUE else FALSE)
}

sd_show_if(
    valid_numer(input$q0) == TRUE ~ "q1"
  )
```

Is there other way to do this with the current features the package has? Any other ideas?

Thanks!
